### ISSUE TITLE
java.lang.System in, out, err

### ISSUE THREAD

**Issue by Saloed** [UnitTestBot/java-stdlib-approximations#1]
Approximate `<clinit>` of `java.lang.System` to provide correct values for  `in, out, err` streams.

**Comment by dog-m** [comment]
Progress on that can be tracked [here](https://github.com/UnitTestBot/java-stdlib-approximations/wiki/Modeling-status#jl-S) *somewhat*.

**Comment by dog-m** [comment]
Blocked by #3

**Comment by dog-m** [comment]
No longer blocked by #3
