### ISSUE TITLE
java.util.LinkedHashSet

### ISSUE THREAD

**Issue by MchKosticyn** [UnitTestBot/java-stdlib-approximations#10]
Collection approximation and decoder

**Comment by dog-m** [comment]
@MchKosticyn , is the current implementation \[[approximation](https://github.com/UnitTestBot/java-stdlib-approximations/blob/main/approximations/src/main/java/generated/java/util/LinkedHashSet.java), [decoder](https://github.com/UnitTestBot/java-stdlib-approximations/blob/main/approximations/src/main/java/decoders/java/util/LinkedHashSet_Decoder.java)\] not suitable or have a problem?

**Comment by MchKosticyn** [comment]
I didn't notice this implementation.
It's suitable. Thanks.
